import { mountWidget } from "./widget";
import {
  getSelfConfig,
  setUserData,
  getUserData,
  getSubDep,
  getSelfId,
  getStaticPath,
  getCurrentUser,
  setViewport,
  callLogin,
  callLoginOut,
} from "./utils";
import { callAuth, addAuth, onLogin } from "../../bridge/index";
import {
  getExhibitFileStreamById,
  getExhibitInfoById,
  getExhibitResultById,
  getExhibitSubFileStreamById,
  getExhibitSubInfoById,
  getExhibitSubResultById,
  getExhibitsAuth,
  getExhibitsByPaging,
  getExhibitFileStreamByWorkId,
  getExhibitInfoByWorkId,
  getExhibitResultByWorkId,
  getExhibitSubFileStreamByWorkId,
  getExhibitSubInfoByWorkId,
  getExhibitSubResultByWorkId,
  getExhibitsByIds,
  getExhibitsDetail,
  getExhibitsSignCount,
} from "./api";
let devData = "";
export const freelogApp: any = {
  mountWidget,
  getExhibitFileStreamById,
  getExhibitInfoById,
  getExhibitResultById,
  getExhibitSubFileStreamById,
  getExhibitSubInfoById,
  getExhibitSubResultById,
  getExhibitsAuth,
  getExhibitsByPaging,
  getExhibitFileStreamByWorkId,
  getExhibitInfoByWorkId,
  getExhibitResultByWorkId,
  getExhibitSubFileStreamByWorkId,
  getExhibitSubInfoByWorkId,
  getExhibitSubResultByWorkId,
  getExhibitsByIds,
  getExhibitsDetail,
  getExhibitsSignCount,
  devData,
  getStaticPath,
  getSubDep,
  getSelfId,
  callAuth,
  addAuth,
  onLogin,
  callLogin,
  callLoginOut,
  getCurrentUser,
  setViewport,
  setUserData,
  getUserData, 
  getSelfConfig,
};
