import {
  getContractInfo,
  getContracts,
  signContract,
  batchSign,
  getTransitionRecords,
  pay,
  getRecord,
  login,
  loginVerify,
  loginOut,
  getCurrent,
  getAccount,
  postRegister,
  getAuthCode,
  verifyAuthCode,
  putResetPassword,
  putResetPayPassword,
} from "./api";
export const freelogAuth: any = {
  getContractInfo,
  getContracts,
  signContract,
  batchSign,
  getTransitionRecords,
  pay,
  getRecord,
  login,
  loginVerify,
  loginOut,
  getCurrent,
  getAccount,
  postRegister,
  getAuthCode,
  verifyAuthCode,
  putResetPassword,
  putResetPayPassword,
};
