import {
  getExhibitListById,
  getExhibitListByPaging,
  getExhibitInfo,
  getExhibitSignCount,
  getExhibitAuthStatus,
  getExhibitAvailable,
  getExhibitFileStream,
  getExhibitDepFileStream,
  getExhibitDepInfo,
  getSignStatistics,
  pushMessage4Task,
  getCollectionSubList,
  getCollectionSubAuth,
  getCollectionSubFileStream,
  getCollectionSubInsideFile,
  getCollectionSubDepFileStream,
  getCollectionSubDepInsideFile
} from "./api";
export const freelogApp: any = {
  getExhibitListById,
  getExhibitListByPaging,
  getExhibitInfo,
  getExhibitSignCount,
  getExhibitAuthStatus,
  getExhibitAvailable,
  getExhibitFileStream,
  getExhibitDepFileStream,
  getExhibitDepInfo,
  getSignStatistics,
  pushMessage4Task,
  getCollectionSubList,
  getCollectionSubAuth,
  getCollectionSubFileStream,
  getCollectionSubInsideFile,
  getCollectionSubDepFileStream,
  getCollectionSubDepInsideFile
};
